source 'https://rubygems.org'

gem 'bootstrap', '~> 4.0.0.alpha3'
gem 'coffee-rails', '~> 4.2'
gem 'devise'
gem 'haml-rails'
gem 'jbuilder', '~> 2.5'
gem 'jquery-rails'
gem 'pg'
gem 'mechanize'
gem 'nokogiri'
gem 'pry'
gem 'puma', '~> 3.0'
gem 'rails', '~> 5.0.0'
gem 'sass-rails', '>= 3.2'
gem 'spring'
gem 'spring-watcher-listen', '~> 2.0.0'
gem 'turbolinks', '~> 5'
gem 'uglifier', '>= 1.3.0'
gem 'whenever', require: false
gem 'will_paginate'
