default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: root
  password:
  timeout: 5000

development:
  <<: *default
  database: xproject_dev

production:
  <<: *default
  database: xproject_production
