# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 867382647968ca2fa4c19cf7308174fa4dc17bcb9a6ac348b51a446b680efe05e96f96f01d6b573c87cd4f7f39586e7ae7eb38e3e50708e7786e51e469c9e993

test:
  secret_key_base: 8593c5033cd270bae0665e91526ad1cf1e66b11e6dbe04e5cf8f5c03e75115c16a0cd47bd9b4547b4fdf417901846ea0e6ea9f0b73587402cbd1143e50f94078

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
